import{ MENUS } from './menus-data';
export const All_menus:MENUS={
    headerNav:[
        {
            'id':1,
            'name':'系统管理',
            'isActive':true
        },
        {
            'id':2,
            'name':'内容管理',
            'isActive':false
        },
        {
            'id':3,
            'name':'扩展模块',
            'isActive':false
        }
    ],
    menuData1:[
        {'title':'后台首页',
        'icon':'fa-address-card',
        'isShow':true,
        'state':'hide',
        'url':'./content',
        'children':[]
        },
        {'title':'我的面板',
        'icon':'fa-telegram ', 
        'isShow':true,  
        'state':'hide',
        'children':[
            {'name':'个人信息','url':'./userinfo'},
            {'name':'修改密码','url':'./password'},
            {'name':'日志信息','url':'./loginfo'}
        ]},
        {'title':'系统设置',
        'icon':'fa-cogs ',
        'isShow':true,  
        'state':'hide',
        'children':[
            {'name':'用户管理','url':'./user-management'},
            {'name':'角色管理','url':'./rule-management'},
            {'name':'菜单管理','url':'./list-management'},
            {'name':'系统参数配置','url':'./sys-option-management'},
            {'name':'系统配置管理','url':'./sys-config-management'},
        ]},
        {'title':'项目文档',
        'icon':'fa-align-justify',
        'isShow':true,  
        'state':'hide',
        'children':[
            {'name':'项目图标示例','url':'./project-demo'},
            {'name':'文档参数说明','url':'./text-option'}
        ]}
      ],
    menuData2:[
        {'title':'后台首页2',
        'icon':'fa-address-card',
        'isShow':true,  
        'state':'hide',
        'url':'./content',
        'children':[
        ]},
        {'title':'我的面板',
        'icon':'fa-telegram ',
        'isShow':true,     
        'state':'hide',
        'children':[
            {'name':'个人信息','url':'./userinfo'},
            {'name':'修改密码','url':'./password'},
            {'name':'日志信息','url':'./loginfo'}
        ]},
        {'title':'系统设置',
        'icon':'fa-cogs ',
        'isShow':true,  
        'state':'hide',
        'children':[
            {'name':'用户管理','url':'./user-management'},
            {'name':'角色管理','url':'./rule-management'},
            {'name':'菜单管理','url':'./list-management'},
            {'name':'系统参数配置','url':'./sys-option-management'},
            {'name':'系统配置管理','url':'./sys-config-management'},
        ]}
      ],
    menuData3:[
        {'title':'后台首页',
        'icon':'fa-address-card',
        'isShow':true,  
        'state':'hide',
        'url':'./content',
        'children':[
        ]},
        {'title':'我的面板',
        'icon':'fa-telegram ',
        'isShow':true,  
        'state':'hide',   
        'children':[
            {'name':'个人信息','url':'./userinfo'},
            {'name':'修改密码','url':'./password'},
            {'name':'日志信息','url':'./loginfo'}
        ]},
        {'title':'系统设置',
        'icon':'fa-cogs ',
        'isShow':true,  
        'state':'hide',
        'children':[
            {'name':'用户管理','url':'./user-management'},
            {'name':'角色管理','url':'./rule-management'},
            {'name':'菜单管理','url':'./list-management'},
            {'name':'系统参数配置','url':'./sys-option-management'},
            {'name':'系统配置管理','url':'./sys-config-management'},
        ]},
        {'title':'项目文档',
        'icon':'fa-align-justify',
        'isShow':true,
        'state':'hide',
        'children':[
            {'name':'项目图标示例','url':'./project-demo'},
            {'name':'文档参数说明','url':'./text-option'}
        ]}
      ]
}
