export const All_menus=[
    {title:'菜单一',
    children:[
        {name:'子菜单一',url:'./content'},
        {name:'子菜单二',url:'1'},
        {name:'子菜单三',url:'2'},
        {name:'子菜单四',url:'3'}
    ]},
    {title:'菜单二',
    children:[
        {name:'子菜单一',url:'4'},
        {name:'子菜单二',url:'5'},
        {name:'子菜单三',url:'6'},
        {name:'子菜单四',url:'7'}
    ]},
    {title:'菜单三',
    children:[
        {name:'子菜单一',url:'8'},
        {name:'子菜单二',url:'9'},
        {name:'子菜单三',url:'10'},
        {name:'子菜单四',url:'12'}
    ]},
    {title:'菜单四',
    children:[
        {name:'子菜单一',url:'11'},
        {name:'子菜单二',url:'13'},
        {name:'子菜单三',url:'14'},
        {name:'子菜单四',url:'15'}
    ]},
  ]